/** Cities / towns for “which voivodeship?” — expanded learning set (major towns & seats). */
export type CityEntry = {
  namePl: string;
  nameEn: string;
  voivId: string;
};

export const CITIES: CityEntry[] = [
  // dolnośląskie 02
  { namePl: "Wrocław", nameEn: "Wrocław", voivId: "02" },
  { namePl: "Wałbrzych", nameEn: "Wałbrzych", voivId: "02" },
  { namePl: "Jelenia Góra", nameEn: "Jelenia Góra", voivId: "02" },
  { namePl: "Legnica", nameEn: "Legnica", voivId: "02" },
  { namePl: "Lubin", nameEn: "Lubin", voivId: "02" },
  { namePl: "Głogów", nameEn: "Głogów", voivId: "02" },
  { namePl: "Świdnica", nameEn: "Świdnica", voivId: "02" },
  { namePl: "Oleśnica", nameEn: "Oleśnica", voivId: "02" },
  { namePl: "Kłodzko", nameEn: "Kłodzko", voivId: "02" },
  { namePl: "Bolesławiec", nameEn: "Bolesławiec", voivId: "02" },
  { namePl: "Zgorzelec", nameEn: "Zgorzelec", voivId: "02" },
  { namePl: "Lubań", nameEn: "Lubań", voivId: "02" },
  { namePl: "Złotoryja", nameEn: "Złotoryja", voivId: "02" },
  { namePl: "Kamienna Góra", nameEn: "Kamienna Góra", voivId: "02" },
  { namePl: "Polkowice", nameEn: "Polkowice", voivId: "02" },
  { namePl: "Trzebnica", nameEn: "Trzebnica", voivId: "02" },
  { namePl: "Wołów", nameEn: "Wołów", voivId: "02" },
  { namePl: "Dzierżoniów", nameEn: "Dzierżoniów", voivId: "02" },
  { namePl: "Jawor", nameEn: "Jawor", voivId: "02" },
  { namePl: "Środa Śląska", nameEn: "Środa Śląska", voivId: "02" },
  { namePl: "Nowa Ruda", nameEn: "Nowa Ruda", voivId: "02" },
  { namePl: "Boguszów-Gorce", nameEn: "Boguszów-Gorce", voivId: "02" },
  // kujawsko-pomorskie 04
  { namePl: "Bydgoszcz", nameEn: "Bydgoszcz", voivId: "04" },
  { namePl: "Toruń", nameEn: "Toruń", voivId: "04" },
  { namePl: "Włocławek", nameEn: "Włocławek", voivId: "04" },
  { namePl: "Grudziądz", nameEn: "Grudziądz", voivId: "04" },
  { namePl: "Inowrocław", nameEn: "Inowrocław", voivId: "04" },
  { namePl: "Brodnica", nameEn: "Brodnica", voivId: "04" },
  { namePl: "Chełmno", nameEn: "Chełmno", voivId: "04" },
  { namePl: "Nakło nad Notecią", nameEn: "Nakło nad Notecią", voivId: "04" },
  { namePl: "Rypin", nameEn: "Rypin", voivId: "04" },
  { namePl: "Świecie", nameEn: "Świecie", voivId: "04" },
  { namePl: "Tuchola", nameEn: "Tuchola", voivId: "04" },
  { namePl: "Żnin", nameEn: "Żnin", voivId: "04" },
  { namePl: "Aleksandrów Kujawski", nameEn: "Aleksandrów Kujawski", voivId: "04" },
  { namePl: "Ciechocinek", nameEn: "Ciechocinek", voivId: "04" },
  { namePl: "Solec Kujawski", nameEn: "Solec Kujawski", voivId: "04" },
  { namePl: "Nowe", nameEn: "Nowe", voivId: "04" },
  // lubelskie 06
  { namePl: "Lublin", nameEn: "Lublin", voivId: "06" },
  { namePl: "Zamość", nameEn: "Zamość", voivId: "06" },
  { namePl: "Chełm", nameEn: "Chełm", voivId: "06" },
  { namePl: "Puławy", nameEn: "Puławy", voivId: "06" },
  { namePl: "Świdnik", nameEn: "Świdnik", voivId: "06" },
  { namePl: "Kraśnik", nameEn: "Kraśnik", voivId: "06" },
  { namePl: "Biłgoraj", nameEn: "Biłgoraj", voivId: "06" },
  { namePl: "Łuków", nameEn: "Łuków", voivId: "06" },
  { namePl: "Tomaszów Lubelski", nameEn: "Tomaszów Lubelski", voivId: "06" },
  { namePl: "Lubartów", nameEn: "Lubartów", voivId: "06" },
  { namePl: "Krasnystaw", nameEn: "Krasnystaw", voivId: "06" },
  { namePl: "Hrubieszów", nameEn: "Hrubieszów", voivId: "06" },
  { namePl: "Nałęczów", nameEn: "Nałęczów", voivId: "06" },
  { namePl: "Janów Lubelski", nameEn: "Janów Lubelski", voivId: "06" },
  { namePl: "Ryki", nameEn: "Ryki", voivId: "06" },
  { namePl: "Łęczna", nameEn: "Łęczna", voivId: "06" },
  // lubuskie 08
  { namePl: "Zielona Góra", nameEn: "Zielona Góra", voivId: "08" },
  { namePl: "Gorzów Wielkopolski", nameEn: "Gorzów Wielkopolski", voivId: "08" },
  { namePl: "Żary", nameEn: "Żary", voivId: "08" },
  { namePl: "Żagań", nameEn: "Żagań", voivId: "08" },
  { namePl: "Nowa Sól", nameEn: "Nowa Sól", voivId: "08" },
  { namePl: "Słubice", nameEn: "Słubice", voivId: "08" },
  { namePl: "Gubin", nameEn: "Gubin", voivId: "08" },
  { namePl: "Kostrzyn nad Odrą", nameEn: "Kostrzyn nad Odrą", voivId: "08" },
  { namePl: "Międzyrzecz", nameEn: "Międzyrzecz", voivId: "08" },
  { namePl: "Sulęcin", nameEn: "Sulęcin", voivId: "08" },
  { namePl: "Strzelce Krajeńskie", nameEn: "Strzelce Krajeńskie", voivId: "08" },
  { namePl: "Świebodzin", nameEn: "Świebodzin", voivId: "08" },
  { namePl: "Wschowa", nameEn: "Wschowa", voivId: "08" },
  { namePl: "Gozdnica", nameEn: "Gozdnica", voivId: "08" },
  // łódzkie 10
  { namePl: "Łódź", nameEn: "Łódź", voivId: "10" },
  { namePl: "Piotrków Trybunalski", nameEn: "Piotrków Trybunalski", voivId: "10" },
  { namePl: "Skierniewice", nameEn: "Skierniewice", voivId: "10" },
  { namePl: "Pabianice", nameEn: "Pabianice", voivId: "10" },
  { namePl: "Zgierz", nameEn: "Zgierz", voivId: "10" },
  { namePl: "Bełchatów", nameEn: "Bełchatów", voivId: "10" },
  { namePl: "Kutno", nameEn: "Kutno", voivId: "10" },
  { namePl: "Sieradz", nameEn: "Sieradz", voivId: "10" },
  { namePl: "Tomaszów Mazowiecki", nameEn: "Tomaszów Mazowiecki", voivId: "10" },
  { namePl: "Zduńska Wola", nameEn: "Zduńska Wola", voivId: "10" },
  { namePl: "Radomsko", nameEn: "Radomsko", voivId: "10" },
  { namePl: "Wieluń", nameEn: "Wieluń", voivId: "10" },
  { namePl: "Opoczno", nameEn: "Opoczno", voivId: "10" },
  { namePl: "Ozorków", nameEn: "Ozorków", voivId: "10" },
  { namePl: "Łowicz", nameEn: "Łowicz", voivId: "10" },
  { namePl: "Rawa Mazowiecka", nameEn: "Rawa Mazowiecka", voivId: "10" },
  { namePl: "Konstantynów Łódzki", nameEn: "Konstantynów Łódzki", voivId: "10" },
  { namePl: "Głowno", nameEn: "Głowno", voivId: "10" },
  // małopolskie 12
  { namePl: "Kraków", nameEn: "Kraków", voivId: "12" },
  { namePl: "Tarnów", nameEn: "Tarnów", voivId: "12" },
  { namePl: "Nowy Sącz", nameEn: "Nowy Sącz", voivId: "12" },
  { namePl: "Oświęcim", nameEn: "Oświęcim", voivId: "12" },
  { namePl: "Chrzanów", nameEn: "Chrzanów", voivId: "12" },
  { namePl: "Zakopane", nameEn: "Zakopane", voivId: "12" },
  { namePl: "Nowy Targ", nameEn: "Nowy Targ", voivId: "12" },
  { namePl: "Bochnia", nameEn: "Bochnia", voivId: "12" },
  { namePl: "Wieliczka", nameEn: "Wieliczka", voivId: "12" },
  { namePl: "Gorlice", nameEn: "Gorlice", voivId: "12" },
  { namePl: "Limanowa", nameEn: "Limanowa", voivId: "12" },
  { namePl: "Brzesko", nameEn: "Brzesko", voivId: "12" },
  { namePl: "Olkusz", nameEn: "Olkusz", voivId: "12" },
  { namePl: "Skawina", nameEn: "Skawina", voivId: "12" },
  { namePl: "Andrychów", nameEn: "Andrychów", voivId: "12" },
  { namePl: "Kęty", nameEn: "Kęty", voivId: "12" },
  { namePl: "Myślenice", nameEn: "Myślenice", voivId: "12" },
  { namePl: "Wadowice", nameEn: "Wadowice", voivId: "12" },
  { namePl: "Sucha Beskidzka", nameEn: "Sucha Beskidzka", voivId: "12" },
  // mazowieckie 14
  { namePl: "Warszawa", nameEn: "Warsaw", voivId: "14" },
  { namePl: "Radom", nameEn: "Radom", voivId: "14" },
  { namePl: "Płock", nameEn: "Płock", voivId: "14" },
  { namePl: "Siedlce", nameEn: "Siedlce", voivId: "14" },
  { namePl: "Pruszków", nameEn: "Pruszków", voivId: "14" },
  { namePl: "Legionowo", nameEn: "Legionowo", voivId: "14" },
  { namePl: "Ostrołęka", nameEn: "Ostrołęka", voivId: "14" },
  { namePl: "Piaseczno", nameEn: "Piaseczno", voivId: "14" },
  { namePl: "Otwock", nameEn: "Otwock", voivId: "14" },
  { namePl: "Ciechanów", nameEn: "Ciechanów", voivId: "14" },
  { namePl: "Żyrardów", nameEn: "Żyrardów", voivId: "14" },
  { namePl: "Mińsk Mazowiecki", nameEn: "Mińsk Mazowiecki", voivId: "14" },
  { namePl: "Wołomin", nameEn: "Wołomin", voivId: "14" },
  { namePl: "Garwolin", nameEn: "Garwolin", voivId: "14" },
  { namePl: "Ząbki", nameEn: "Ząbki", voivId: "14" },
  { namePl: "Marki", nameEn: "Marki", voivId: "14" },
  { namePl: "Pułtusk", nameEn: "Pułtusk", voivId: "14" },
  { namePl: "Płońsk", nameEn: "Płońsk", voivId: "14" },
  { namePl: "Grójec", nameEn: "Grójec", voivId: "14" },
  { namePl: "Nowy Dwór Mazowiecki", nameEn: "Nowy Dwór Mazowiecki", voivId: "14" },
  // opolskie 16
  { namePl: "Opole", nameEn: "Opole", voivId: "16" },
  { namePl: "Kędzierzyn-Koźle", nameEn: "Kędzierzyn-Koźle", voivId: "16" },
  { namePl: "Nysa", nameEn: "Nysa", voivId: "16" },
  { namePl: "Brzeg", nameEn: "Brzeg", voivId: "16" },
  { namePl: "Kluczbork", nameEn: "Kluczbork", voivId: "16" },
  { namePl: "Prudnik", nameEn: "Prudnik", voivId: "16" },
  { namePl: "Strzelce Opolskie", nameEn: "Strzelce Opolskie", voivId: "16" },
  { namePl: "Namysłów", nameEn: "Namysłów", voivId: "16" },
  { namePl: "Krapkowice", nameEn: "Krapkowice", voivId: "16" },
  { namePl: "Głubczyce", nameEn: "Głubczyce", voivId: "16" },
  { namePl: "Zdzieszowice", nameEn: "Zdzieszowice", voivId: "16" },
  // podkarpackie 18
  { namePl: "Rzeszów", nameEn: "Rzeszów", voivId: "18" },
  { namePl: "Przemyśl", nameEn: "Przemyśl", voivId: "18" },
  { namePl: "Krosno", nameEn: "Krosno", voivId: "18" },
  { namePl: "Jarosław", nameEn: "Jarosław", voivId: "18" },
  { namePl: "Sanok", nameEn: "Sanok", voivId: "18" },
  { namePl: "Mielec", nameEn: "Mielec", voivId: "18" },
  { namePl: "Stalowa Wola", nameEn: "Stalowa Wola", voivId: "18" },
  { namePl: "Tarnobrzeg", nameEn: "Tarnobrzeg", voivId: "18" },
  { namePl: "Łańcut", nameEn: "Łańcut", voivId: "18" },
  { namePl: "Leżajsk", nameEn: "Leżajsk", voivId: "18" },
  { namePl: "Jasło", nameEn: "Jasło", voivId: "18" },
  { namePl: "Lubaczów", nameEn: "Lubaczów", voivId: "18" },
  { namePl: "Dębica", nameEn: "Dębica", voivId: "18" },
  { namePl: "Przeworsk", nameEn: "Przeworsk", voivId: "18" },
  { namePl: "Nisko", nameEn: "Nisko", voivId: "18" },
  // podlaskie 20
  { namePl: "Białystok", nameEn: "Białystok", voivId: "20" },
  { namePl: "Suwałki", nameEn: "Suwałki", voivId: "20" },
  { namePl: "Łomża", nameEn: "Łomża", voivId: "20" },
  { namePl: "Bielsk Podlaski", nameEn: "Bielsk Podlaski", voivId: "20" },
  { namePl: "Hajnówka", nameEn: "Hajnówka", voivId: "20" },
  { namePl: "Sokółka", nameEn: "Sokółka", voivId: "20" },
  { namePl: "Augustów", nameEn: "Augustów", voivId: "20" },
  { namePl: "Grajewo", nameEn: "Grajewo", voivId: "20" },
  { namePl: "Zambrów", nameEn: "Zambrów", voivId: "20" },
  { namePl: "Mońki", nameEn: "Mońki", voivId: "20" },
  { namePl: "Siemiatycze", nameEn: "Siemiatycze", voivId: "20" },
  { namePl: "Kolno", nameEn: "Kolno", voivId: "20" },
  // pomorskie 22
  { namePl: "Gdańsk", nameEn: "Gdańsk", voivId: "22" },
  { namePl: "Gdynia", nameEn: "Gdynia", voivId: "22" },
  { namePl: "Sopot", nameEn: "Sopot", voivId: "22" },
  { namePl: "Słupsk", nameEn: "Słupsk", voivId: "22" },
  { namePl: "Wejherowo", nameEn: "Wejherowo", voivId: "22" },
  { namePl: "Rumia", nameEn: "Rumia", voivId: "22" },
  { namePl: "Malbork", nameEn: "Malbork", voivId: "22" },
  { namePl: "Tczew", nameEn: "Tczew", voivId: "22" },
  { namePl: "Starogard Gdański", nameEn: "Starogard Gdański", voivId: "22" },
  { namePl: "Kościerzyna", nameEn: "Kościerzyna", voivId: "22" },
  { namePl: "Kartuzy", nameEn: "Kartuzy", voivId: "22" },
  { namePl: "Puck", nameEn: "Puck", voivId: "22" },
  { namePl: "Pruszcz Gdański", nameEn: "Pruszcz Gdański", voivId: "22" },
  { namePl: "Reda", nameEn: "Reda", voivId: "22" },
  { namePl: "Chojnice", nameEn: "Chojnice", voivId: "22" },
  { namePl: "Lębork", nameEn: "Lębork", voivId: "22" },
  // śląskie 24
  { namePl: "Katowice", nameEn: "Katowice", voivId: "24" },
  { namePl: "Częstochowa", nameEn: "Częstochowa", voivId: "24" },
  { namePl: "Gliwice", nameEn: "Gliwice", voivId: "24" },
  { namePl: "Bielsko-Biała", nameEn: "Bielsko-Biała", voivId: "24" },
  { namePl: "Rybnik", nameEn: "Rybnik", voivId: "24" },
  { namePl: "Tychy", nameEn: "Tychy", voivId: "24" },
  { namePl: "Dąbrowa Górnicza", nameEn: "Dąbrowa Górnicza", voivId: "24" },
  { namePl: "Chorzów", nameEn: "Chorzów", voivId: "24" },
  { namePl: "Jaworzno", nameEn: "Jaworzno", voivId: "24" },
  { namePl: "Jastrzębie-Zdrój", nameEn: "Jastrzębie-Zdrój", voivId: "24" },
  { namePl: "Mysłowice", nameEn: "Mysłowice", voivId: "24" },
  { namePl: "Siemianowice Śląskie", nameEn: "Siemianowice Śląskie", voivId: "24" },
  { namePl: "Ruda Śląska", nameEn: "Ruda Śląska", voivId: "24" },
  { namePl: "Zabrze", nameEn: "Zabrze", voivId: "24" },
  { namePl: "Bytom", nameEn: "Bytom", voivId: "24" },
  { namePl: "Piekary Śląskie", nameEn: "Piekary Śląskie", voivId: "24" },
  { namePl: "Świętochłowice", nameEn: "Świętochłowice", voivId: "24" },
  { namePl: "Racibórz", nameEn: "Racibórz", voivId: "24" },
  { namePl: "Wodzisław Śląski", nameEn: "Wodzisław Śląski", voivId: "24" },
  { namePl: "Zawiercie", nameEn: "Zawiercie", voivId: "24" },
  // świętokrzyskie 26
  { namePl: "Kielce", nameEn: "Kielce", voivId: "26" },
  { namePl: "Ostrowiec Świętokrzyski", nameEn: "Ostrowiec Świętokrzyski", voivId: "26" },
  { namePl: "Starachowice", nameEn: "Starachowice", voivId: "26" },
  { namePl: "Końskie", nameEn: "Końskie", voivId: "26" },
  { namePl: "Sandomierz", nameEn: "Sandomierz", voivId: "26" },
  { namePl: "Busko-Zdrój", nameEn: "Busko-Zdrój", voivId: "26" },
  { namePl: "Jędrzejów", nameEn: "Jędrzejów", voivId: "26" },
  { namePl: "Skarżysko-Kamienna", nameEn: "Skarżysko-Kamienna", voivId: "26" },
  { namePl: "Kazimierza Wielka", nameEn: "Kazimierza Wielka", voivId: "26" },
  { namePl: "Opatów", nameEn: "Opatów", voivId: "26" },
  // warmińsko-mazurskie 28
  { namePl: "Olsztyn", nameEn: "Olsztyn", voivId: "28" },
  { namePl: "Elbląg", nameEn: "Elbląg", voivId: "28" },
  { namePl: "Ełk", nameEn: "Ełk", voivId: "28" },
  { namePl: "Iława", nameEn: "Iława", voivId: "28" },
  { namePl: "Ostróda", nameEn: "Ostróda", voivId: "28" },
  { namePl: "Giżycko", nameEn: "Giżycko", voivId: "28" },
  { namePl: "Bartoszyce", nameEn: "Bartoszyce", voivId: "28" },
  { namePl: "Kętrzyn", nameEn: "Kętrzyn", voivId: "28" },
  { namePl: "Mrągowo", nameEn: "Mrągowo", voivId: "28" },
  { namePl: "Działdowo", nameEn: "Działdowo", voivId: "28" },
  { namePl: "Pisz", nameEn: "Pisz", voivId: "28" },
  { namePl: "Szczytno", nameEn: "Szczytno", voivId: "28" },
  { namePl: "Lidzbark Warmiński", nameEn: "Lidzbark Warmiński", voivId: "28" },
  { namePl: "Braniewo", nameEn: "Braniewo", voivId: "28" },
  // wielkopolskie 30
  { namePl: "Poznań", nameEn: "Poznań", voivId: "30" },
  { namePl: "Kalisz", nameEn: "Kalisz", voivId: "30" },
  { namePl: "Konin", nameEn: "Konin", voivId: "30" },
  { namePl: "Piła", nameEn: "Piła", voivId: "30" },
  { namePl: "Ostrów Wielkopolski", nameEn: "Ostrów Wielkopolski", voivId: "30" },
  { namePl: "Gniezno", nameEn: "Gniezno", voivId: "30" },
  { namePl: "Leszno", nameEn: "Leszno", voivId: "30" },
  { namePl: "Swarzędz", nameEn: "Swarzędz", voivId: "30" },
  { namePl: "Luboń", nameEn: "Luboń", voivId: "30" },
  { namePl: "Kościan", nameEn: "Kościan", voivId: "30" },
  { namePl: "Śrem", nameEn: "Śrem", voivId: "30" },
  { namePl: "Września", nameEn: "Września", voivId: "30" },
  { namePl: "Krotoszyn", nameEn: "Krotoszyn", voivId: "30" },
  { namePl: "Rawicz", nameEn: "Rawicz", voivId: "30" },
  { namePl: "Gostyń", nameEn: "Gostyń", voivId: "30" },
  { namePl: "Chodzież", nameEn: "Chodzież", voivId: "30" },
  { namePl: "Wągrowiec", nameEn: "Wągrowiec", voivId: "30" },
  { namePl: "Trzcianka", nameEn: "Trzcianka", voivId: "30" },
  { namePl: "Złotów", nameEn: "Złotów", voivId: "30" },
  { namePl: "Szamotuły", nameEn: "Szamotuły", voivId: "30" },
  // zachodniopomorskie 32
  { namePl: "Szczecin", nameEn: "Szczecin", voivId: "32" },
  { namePl: "Koszalin", nameEn: "Koszalin", voivId: "32" },
  { namePl: "Stargard", nameEn: "Stargard", voivId: "32" },
  { namePl: "Kołobrzeg", nameEn: "Kołobrzeg", voivId: "32" },
  { namePl: "Świnoujście", nameEn: "Świnoujście", voivId: "32" },
  { namePl: "Police", nameEn: "Police", voivId: "32" },
  { namePl: "Goleniów", nameEn: "Goleniów", voivId: "32" },
  { namePl: "Gryfino", nameEn: "Gryfino", voivId: "32" },
  { namePl: "Myślibórz", nameEn: "Myślibórz", voivId: "32" },
  { namePl: "Wałcz", nameEn: "Wałcz", voivId: "32" },
  { namePl: "Drawsko Pomorskie", nameEn: "Drawsko Pomorskie", voivId: "32" },
  { namePl: "Szczecinek", nameEn: "Szczecinek", voivId: "32" },
  { namePl: "Białogard", nameEn: "Białogard", voivId: "32" },
  { namePl: "Łobez", nameEn: "Łobez", voivId: "32" },
  { namePl: "Gryfice", nameEn: "Gryfice", voivId: "32" }
];
